export type SourceModule = {
  name: string;
  path: string;
  body: string;
};

export const SOURCE_MODULES: SourceModule[] = [
  {
    name: "charging-station.graphql",
    path: "source/charging-station.graphql",
    body: `type ChargingStation {
  id: ID!
  name: String!
  operator: String!
  stationCode: String!
  location: GeoJSON! @geoPoint(shape: POINT)
  address: Address
  availability: StationAvailability!
  chargingPoints: [ChargingPointInfo!]!
}`
  },
  {
    name: "charging-point-info.graphql",
    path: "source/charging-point-info.graphql",
    body: `type ChargingPointInfo {
  id: ID!
  availableNow: Boolean!
  outOfService: Boolean!
  connectors: [ConnectorInfo!]!
}`
  },
  {
    name: "connector-info.graphql",
    path: "source/connector-info.graphql",
    body: `type ConnectorInfo {
  type: ConnectorType!
  powerKw: Float!
  tethered: Boolean
}`
  },
  {
    name: "enums.graphql",
    path: "source/enums.graphql",
    body: `enum ConnectorType {
  CCS
  CHAdeMO
  SCHUKO
  TYPE1
  TYPE2
}`
  }
];

export const COMPOSED_PREVIEW = `directive @geoPoint(shape: GeoPointShape!) on FIELD_DEFINITION

"""A GeoJSON object as defined by RFC 7946."""
scalar GeoJSON @specifiedBy(url: "https://the-guild.dev/graphql/scalars/docs/scalars/geo-json")

type ChargingStation {
  id: ID!
  name: String!
  operator: String!
  stationCode: String!
  location: GeoJSON! @geoPoint(shape: POINT)
  address: Address
  availability: StationAvailability!
  chargingPoints: [ChargingPointInfo!]!
}

type ChargingPointInfo {
  id: ID!
  availableNow: Boolean!
  outOfService: Boolean!
  connectors: [ConnectorInfo!]!
}

type ConnectorInfo {
  type: ConnectorType!
  powerKw: Float!
  tethered: Boolean
}

enum ConnectorType { CCS CHAdeMO SCHUKO TYPE1 TYPE2 }

# ... plus Address, StationAvailability, Vehicle, ChargingSession, ...`;

export const BACKEND_TYPES_PREVIEW = `// generated by @graphql-codegen/typescript
// backend/src/graphql/generated/graphql.ts

export type ChargingStation = {
  __typename?: 'ChargingStation';
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  operator: Scalars['String']['output'];
  stationCode: Scalars['String']['output'];
  location: Scalars['GeoJSON']['output'];
  address?: Maybe<Address>;
  availability: StationAvailability;
  chargingPoints: Array<ChargingPointInfo>;
};

export type ConnectorInfo = {
  __typename?: 'ConnectorInfo';
  type: ConnectorType;
  powerKw: Scalars['Float']['output'];
  tethered?: Maybe<Scalars['Boolean']['output']>;
};

export enum ConnectorType {
  Ccs = 'CCS',
  ChAdeMo = 'CHAdeMO',
  Schuko = 'SCHUKO',
  Type1 = 'TYPE1',
  Type2 = 'TYPE2'
}

export type Resolvers<ContextType = GraphQLContext> = {
  ChargingStation?: ChargingStationResolvers<ContextType>;
  ConnectorInfo?: ConnectorInfoResolvers<ContextType>;
  // ...
};`;

export const FRONTEND_HOOKS_PREVIEW = `// generated by @graphql-codegen/client-preset
// frontend/src/graphql/generated/graphql.ts

import { useQuery } from '@apollo/client';

export type StationSummaryFragment = {
  __typename?: 'ChargingStation';
  id: string;
  name: string;
  operator: string;
  availability: {
    totalPoints: number;
    availableNowPoints: number;
    operationalPoints: number;
  };
};

export const StationsNearDocument = gql\`
  query StationsNear($center: GeoJSON!, $radiusKm: Float!) {
    stationsNear(center: $center, radiusKm: $radiusKm) {
      ...StationSummary
    }
  }
\`;

export function useStationsNearQuery(
  variables: StationsNearQueryVariables
) {
  return useQuery<StationsNearQuery>(StationsNearDocument, { variables });
}`;
